/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectoracing2dforwindows.views;

import java.util.logging.Level;
import java.util.logging.Logger;
import proyectoracing2dforwindows.exceptions.CheckpointException;
import proyectoracing2dforwindows.exceptions.FileManagerException;
import proyectoracing2dforwindows.exceptions.InvalidMapFormatException;
import proyectoracing2dforwindows.exceptions.MapFileNotFoundException;
import proyectoracing2dforwindows.interfaces.ClickListener;

/**
 *
 * @author david
 */
public class AboutUsPanel extends javax.swing.JPanel {
    private ClickListener clickListener;
    /**
     * Creates new form AboutUsPanel
     */
    public AboutUsPanel( ClickListener clickListener) {
        initComponents();
        this.clickListener=clickListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bReturn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(900, 900));
        setPreferredSize(new java.awt.Dimension(900, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bReturn.setBackground(new java.awt.Color(204, 204, 204));
        bReturn.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        bReturn.setText("RETURN");
        bReturn.setAlignmentX(20.0F);
        bReturn.setAlignmentY(20.0F);
        bReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReturnActionPerformed(evt);
            }
        });
        add(bReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 830, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("third semester students of systems engineering");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Universidad Autónoma de Manizales");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 227, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Santiago Castaño Arcila");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thomas Alejandro Toro Herrera");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("David Esteban Toro Herrera");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("This project was developed by");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 50)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("of de");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Developers:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReturnActionPerformed
        try {
            // TODO add your handling code here:
            clickListener.showInitialMenu();
        } catch (FileManagerException ex) {
            Logger.getLogger(AboutUsPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MapFileNotFoundException ex) {
            Logger.getLogger(AboutUsPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidMapFormatException ex) {
            Logger.getLogger(AboutUsPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CheckpointException ex) {
            Logger.getLogger(AboutUsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bReturnActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
