/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectoracing2dforwindows.views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.swing.Timer;

/**
 *
 * @author usuario
 */
public class DoubleBufferExample extends javax.swing.JPanel {

    
    private BufferedImage buffer; // Búfer de imagen
    private int x = 0;
    private int y = 0;

    public DoubleBufferExample() {
        // Tamaño de la ventana
        setPreferredSize(new Dimension(400, 400));

        // Crear el búfer de imagen con el mismo tamaño que el JPanel
        buffer = new BufferedImage(getPreferredSize().width, getPreferredSize().height, BufferedImage.TYPE_INT_ARGB);

        // Iniciar un temporizador para actualizar la animación
        Timer timer = new Timer(30, e -> {
            // Actualizar las coordenadas de la animación
            x += 5;
            y += 5;

            // Volver a dibujar en el búfer de imagen
            Graphics2D g2d = buffer.createGraphics();
            paintComponent(g2d);
            g2d.dispose();

            // Volver a dibujar en el JPanel
            repaint();
        });
        timer.start();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Dibujar en el búfer de imagen
        Graphics2D g2dBuffer = buffer.createGraphics();
        g2dBuffer.setColor(Color.RED);
        g2dBuffer.fillOval(x, y, 50, 50);
        g2dBuffer.dispose();

        // Copiar el contenido del búfer de imagen al JPanel
        g.drawImage(buffer, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
