/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectoracing2dforwindows.views;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import proyectoracing2dforwindows.interfaces.Drawable;
import proyectoracing2dforwindows.interfaces.KeyListener;
import proyectoracing2dforwindows.interfaces.Paintable;
import proyectoracing2dforwindows.models.Runway;

/**
 *
 * @author usuario
 */
public class GamePanel extends javax.swing.JPanel implements Paintable{
    
    private Runway runway;
    KeyListener keylistener;
    private Graphics g;
    private Drawable drawable;
    
    public GamePanel(KeyListener keylistener, Drawable drawable) {
        this.drawable = drawable;
        this.drawable.setPaint(this);
        initComponents();
        
        this.keylistener=keylistener;
        setFocusTraversalKeysEnabled(false); // Desactivar el paso de foco para evitar interferencias con los eventos de teclado
        
    }
    
    
    @Override
    protected void paintComponent(Graphics g) {
        runway.draw((Graphics2D)g);
        try {
            drawable.drawElements(g);
        } catch (InterruptedException ex) {
            Logger.getLogger(GamePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    public void setRunway(Runway runway) {
        this.runway = runway;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GamePanel.this.keyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressed
        // TODO add your handling code here:
        keylistener.formKeyPressed(evt);
    }//GEN-LAST:event_keyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        keylistener.formKeyReleased(evt);
    }//GEN-LAST:event_formKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
