/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectoracing2dforwindows.views;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyectoracing2dforwindows.exceptions.CheckpointException;
import proyectoracing2dforwindows.exceptions.FileManagerException;
import proyectoracing2dforwindows.exceptions.InvalidMapFormatException;
import proyectoracing2dforwindows.exceptions.MapFileNotFoundException;
import proyectoracing2dforwindows.interfaces.ClickListener;

/**
 *
 * @author david
 */
public class InitialMenu extends javax.swing.JPanel {
    private ClickListener clickListener;
    
    /**
     * Creates new form InitialMenu
     */
    public InitialMenu(ClickListener clickListener) {
        initComponents();
        this.clickListener = clickListener;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bPlay = new javax.swing.JButton();
        bOptions = new javax.swing.JButton();
        bAboutUs = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setMinimumSize(new java.awt.Dimension(900, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bPlay.setFont(bPlay.getFont().deriveFont(bPlay.getFont().getSize()+58f));
        bPlay.setText("PLAY");
        bPlay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPlayActionPerformed(evt);
            }
        });
        jPanel1.add(bPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 230, 88));

        bOptions.setFont(bPlay.getFont());
        bOptions.setText("OPTIONS");
        bOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOptionsActionPerformed(evt);
            }
        });
        jPanel1.add(bOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        bAboutUs.setFont(bPlay.getFont());
        bAboutUs.setText("ABOUT US");
        bAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAboutUsActionPerformed(evt);
            }
        });
        jPanel1.add(bAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        bExit.setText("EXIT");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        jPanel1.add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data.gifs/IntroVideoMenu.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 910));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPlayActionPerformed
        // TODO add your handling code here:
        System.out.println("play");
        
        try {
            clickListener.showMapSelector();
        } catch (FileManagerException | MapFileNotFoundException | InvalidMapFormatException | CheckpointException ex) {
            JOptionPane.showMessageDialog(this,
            "An error occurred while initializing the game: " + ex.getMessage(),
            "Initialization Error",
            JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_bPlayActionPerformed

    private void bOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOptionsActionPerformed
        // TODO add your handling code here:
        System.out.println("options");
        clickListener.showOptionsPanel();

        
    }//GEN-LAST:event_bOptionsActionPerformed
    
    private void bAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutUsActionPerformed
        // TODO add your handling code here:
        clickListener.showAboutUsPanel();
        

        
    }//GEN-LAST:event_bAboutUsActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAboutUs;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bOptions;
    private javax.swing.JButton bPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the optionType
     */
    
}
