/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectoracing2dforwindows.views;

import java.util.logging.Level;
import java.util.logging.Logger;
import proyectoracing2dforwindows.exceptions.FileManagerException;
import proyectoracing2dforwindows.exceptions.InvalidMapFormatException;
import proyectoracing2dforwindows.exceptions.MapFileNotFoundException;
import proyectoracing2dforwindows.interfaces.ClickListener;

/**
 *
 * @author david
 */
public class OptionsPanel extends javax.swing.JPanel {
    private ClickListener clickListener;
    /**
     * Creates new form OptionsPanel
     */
    public OptionsPanel(ClickListener clickListener) {
        initComponents();
        this.clickListener=clickListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bReturn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sSetNumLaps = new javax.swing.JSpinner();
        sSetNumPowers = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bSelectCarPlayer1 = new javax.swing.JButton();
        bSelectCarPlayer2 = new javax.swing.JButton();
        bSelecUserNamePlayer1 = new javax.swing.JButton();
        bSelectUserNamePlayer2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 900));
        setMinimumSize(new java.awt.Dimension(900, 900));
        setPreferredSize(new java.awt.Dimension(900, 900));

        bReturn.setFont(sSetNumLaps.getFont());
        bReturn.setText("RETURN");
        bReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReturnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 70)); // NOI18N
        jLabel2.setText("Number of laps");

        jLabel3.setFont(jLabel2.getFont());
        jLabel3.setText("Number of powers");

        sSetNumLaps.setFont(new java.awt.Font("Tw Cen MT", 0, 40)); // NOI18N
        sSetNumLaps.setPreferredSize(new java.awt.Dimension(90, 60));

        sSetNumPowers.setFont(sSetNumLaps.getFont());
        sSetNumPowers.setMinimumSize(new java.awt.Dimension(90, 60));
        sSetNumPowers.setPreferredSize(new java.awt.Dimension(90, 60));

        jLabel1.setFont(jLabel2.getFont());
        jLabel1.setText("Settings player 1");

        jLabel4.setFont(jLabel2.getFont());
        jLabel4.setText("Settings player 2");

        bSelectCarPlayer1.setFont(new java.awt.Font("Tw Cen MT", 0, 40)); // NOI18N
        bSelectCarPlayer1.setText("SELECT");
        bSelectCarPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelectCarPlayer1ActionPerformed(evt);
            }
        });

        bSelectCarPlayer2.setFont(bSelectCarPlayer1.getFont());
        bSelectCarPlayer2.setText("SELECT");

        bSelecUserNamePlayer1.setFont(bSelectCarPlayer1.getFont());
        bSelecUserNamePlayer1.setText("Select");

        bSelectUserNamePlayer2.setFont(bSelecUserNamePlayer1.getFont());
        bSelectUserNamePlayer2.setText("Select");

        jLabel5.setFont(bSelectCarPlayer1.getFont());
        jLabel5.setText("Select car");

        jLabel6.setFont(bSelectCarPlayer1.getFont());
        jLabel6.setText("Select car");

        jLabel7.setFont(bSelectCarPlayer1.getFont());
        jLabel7.setText("Select user name");

        jLabel8.setFont(bSelectCarPlayer1.getFont());
        jLabel8.setText("Select user name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(bSelectCarPlayer2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(bSelectCarPlayer1)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bSelecUserNamePlayer1)
                                    .addComponent(bSelectUserNamePlayer2)))
                            .addComponent(bReturn)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sSetNumLaps, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(31, 31, 31)
                            .addComponent(sSetNumPowers, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(670, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sSetNumLaps, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sSetNumPowers, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bSelectCarPlayer1)
                    .addComponent(jLabel7)
                    .addComponent(bSelecUserNamePlayer1))
                .addGap(75, 75, 75)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bSelectCarPlayer2)
                    .addComponent(jLabel8)
                    .addComponent(bSelectUserNamePlayer2))
                .addGap(57, 57, 57)
                .addComponent(bReturn)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReturnActionPerformed
        try {
            // TODO add your handling code here:
            clickListener.showInitialMenu();
        } catch (FileManagerException ex) {
            Logger.getLogger(OptionsPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MapFileNotFoundException ex) {
            Logger.getLogger(OptionsPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidMapFormatException ex) {
            Logger.getLogger(OptionsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bReturnActionPerformed

    private void bSelectCarPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelectCarPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSelectCarPlayer1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bReturn;
    private javax.swing.JButton bSelecUserNamePlayer1;
    private javax.swing.JButton bSelectCarPlayer1;
    private javax.swing.JButton bSelectCarPlayer2;
    private javax.swing.JButton bSelectUserNamePlayer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner sSetNumLaps;
    private javax.swing.JSpinner sSetNumPowers;
    // End of variables declaration//GEN-END:variables
}
