/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoracing2dforwindows.views;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import proyectoracing2dforwindows.managers.MapManager;
import proyectoracing2dforwindows.models.Car;
import proyectoracing2dforwindows.models.Runway;

/**
 *
 * @author usuario
 */
public class PruebaPista extends javax.swing.JFrame {
    private BufferedImage image;
    URL imageUrl = getClass().getResource("/data/images/carro.png");

    MapManager mapManager;
    Runway runway;
    Car car1;
    public void setMapManager(MapManager mapManager) {
        this.mapManager = mapManager;
    }

    public void setRunway(Runway runway) {
        this.runway = runway;
    }
    
    
    
    public PruebaPista() throws IOException {
        initComponents();
        
        image = javax.imageio.ImageIO.read(imageUrl);    
        
        runway = null;
    }

    @Override
    public void paint(Graphics g){

        if(runway != null){
            runway.draw(g);
            car1=new Car(0, 0, 0, 10, 10, "Carro1", image, imageUrl);
            car1.draw(g);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(949, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(854, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mapManager.loadRunways(0, 0);
        System.out.println(mapManager.getRunwaysNames());
        runway = mapManager.getRunway("Pista1");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        PruebaPista window = new PruebaPista();
        MapManager mapManager = new MapManager();
        window.setMapManager(mapManager);
        window.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
